- name: "build mariadb docker"
  docker_container:
    name: db-mvlb
    image: mariadb:latest
    state: started
    published_ports: 33061:3306
    restart_policy: always
    volumes: 'db_data:/var/lib/mysql'
    env:
      MYSQL_ROOT_PASSWORD: {{MYSQL_ROOT_PASSWORD}}
      MYSQL_DATABASE: {{MYSQL_DATABASE}}
      MYSQL_USER: {{MYSQL_USER}}
      MYSQL_PASSWORD: {{MYSQL_PASSWORD}}

- name: "build wordpress docker"
  docker_container:
    name: wp-mvlb
    image: wordpress
    state: started
    published_ports: 80:80
    restart_policy: always
    volumes: 'wordpress:/var/www/html'
    env:
      WORDPRESS_DB_HOST: 172.17.0.2:3306
      WORDPRESS_DB_USER: {{MYSQL_USER}}
      WORDPRESS_DB_PASSWORD: {{MYSQL_PASSWORD}}
      WORDPRESS_DB_NAME: {{MYSQL_DATABASE}}